title: Sandeep Kumar Soni
logo: /profile.jpg
#<img src="profile.jpg" alt="My Photo" style="width:200px;">
#description: text below image
show_downloads: true
title: "Welcome to My Academic Webpage"
description: "An overview of my academic work, research, and publications."
theme: jekyll-theme-cayman
