title: "Sandeep Kumar Soni"
logo: "/profile3.jpg"
theme: jekyll-theme-minimal
show_downloads: true
description: >
<div style="text-align: center;">
  <a href="./my_cv.pdf" download>
    <img src="/cv.png" alt="Download CV" style="width:30px; height:30px; margin-right: 10px;">
  </a>
  <a href="https://scholar.google.com/citations?hl=en&user=zXOJ0cQAAAAJ" target="_blank">
    <img src="/google-scholar-icon.png" alt="Google Scholar" style="width:30px; height:30px; margin-right: 10px;">
  </a>
  <a href="https://www.linkedin.com/in/sandeep-soni-90bbb3243/" target="_blank">
    <img src="/linkedin.png" alt="LinkedIn" style="width:30px; height:30px;">
  </a>
</div>



