title: "Sandeep Kumar Soni"
logo: "/profile3.jpg"
theme: jekyll-theme-minimal
show_downloads: true
description: >
  <div class="custom-links" style="text-align: center;">
    <a href="/My_CV.pdf" download>
      <img src="/cv.png" alt="Download CV">
    </a>
    <a href="https://scholar.google.com/citations?hl=en&user=zXOJ0cQAAAAJ" target="_blank">
      <img src="/google-scholar-icon.png" alt="Google Scholar">
    </a>
    <a href="https://www.linkedin.com/in/sandeep-soni-90bbb3243/" target="_blank">
      <img src="/linkedin.png" alt="LinkedIn">
    </a>
  </div>


