title: "Sandeep Kumar Soni"
logo: "/profile3.jpg"
theme: jekyll-theme-minimal
show_downloads: True

# Remove GitHub Ribbon
github:
  ribbon: false

# Remove GitHub Repository Link
repository: false

# Remove Footer Credit
footer:
  powered_by: false




