title: Sandeep Kumar Soni
logo: /profile3.jpg
#<img src="profile.jpg" alt="My Photo" style="width:200px;">
#description: text below image
show_downloads: true
## Downloads and Links
- [Download My CV](./path-to-your-cv/My_CV.pdf)
- [My Google Scholar Profile](https://scholar.google.com/citations?hl=en&user=zXOJ0cQAAAAJ)
- [Connect with Me on LinkedIn](https://www.linkedin.com/in/sandeep-soni-90bbb3243/)

title: "Sandeep Kumar Soni"
#description: "An overview of my academic work, research, and publications."
theme: jekyll-theme-minimal
