title: "Sandeep Kumar Soni"
logo: "/profile3.jpg"
theme: jekyll-theme-minimal
show_downloads: true

# GitHub Settings
github:
  ribbon: false # This might not work depending on the theme

# Repository Link (if applicable, might not work in this theme)
repository: false

# Custom Footer Configuration (not supported natively by most themes)
footer:
  powered_by: false # This will likely need custom CSS to actually work



